modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile = "pixelcringe_icon.png"
logoBlur = false
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "pixelmon"
    versionRange = "[9.3.0,)"
    ordering = "NONE"
    side = "BOTH"
